# Generated by Django 4.2.14 on 2024-08-13 18:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title_ru', models.CharField(blank=True, max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('year', models.PositiveIntegerField(blank=True)),
                ('poster_url', models.ImageField(blank=True, upload_to='movies/%Y')),
            ],
        ),
    ]
