# Generated by Django 4.2.14 on 2024-08-25 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_country_remove_movie_country_movie_reated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='reated_at',
            new_name='related_at',
        ),
    ]
